### ISSUE TITLE
Admin view results

### ISSUE THREAD

**Issue by huytbt** [huytbt/vote#14]
Nếu các user chưa vote hết thì admin vẫn có thể xem được kết quả hiện tại

**Comment by autn** [comment]
Admin luôn xem được kết quả hiện tại, anh bấm "Tạo kết quả" nó sẽ ra kết quả tại thời điểm đó, sau này nếu có người bình chọn thêm thì anh lại bấm "Tạo kết quả" thì sẽ được cập nhật ở thời điểm mới.

**Comment by autn** [comment]
Ngoài tạo kết quả để xem thì hiện tại Admin có thể xem chit tiết bình chọn qua "Kết quả chi tiết". Em close issue này, coi như hoàn chỉnh 2.0, chờ bản nâng cấp tiếp :D
