### ISSUE TITLE
Move method allUser from Votes model to User model

### ISSUE THREAD

**Issue by huytbt** [huytbt/vote#4]
Hàm của user thì nên nằm ở model User

**Comment by autn** [comment]
Cái này thực chất là một hàm nhỏ gọi tất cả user nằm trong danh sách bình chọn ra một listData, gọi ở đây sẽ sử dụng ở View được luôn. Nếu khai báo ở User model thì ở Vote cũng phải viết 1 hàm để gọi lại.
